#!/bin/bash
# group by l_orderkey, having sum qunatity >300
cat lineitem.csv | tr '.,' ',.' | datamash -H -t\; -g1 sum 5 | awk -F\; '
	NR==1 || $2>300 { print $0 } ' |\
# O >< L (orderkey)
join --header -t\; -1 1 -2 1 orders.csv - > join1.csv

#c_name,c_custkey,o_orderkey,o_orderdate,o_totalprice
head -1 join1.csv | cut -d\; -f1,2,4,5,10 > tmp1.csv
tail -n+2 join1.csv | cut -d\; -f1,2,4,5,10 | sort -t\; -k2,2 >> tmp1.csv
cut -d\; -f1,2 customer.csv |
join --header -t\; -1 1 -2 2 -o 1.2 0 2.1 2.3 2.2 2.4 2.5 - tmp1.csv > join2.csv
head -1 join2.csv;
tail -n+2 join2.csv | sort -t\; -k6 | sort -t\; -k4,4 -r | head -100

rm tmp*.csv join1.csv join2.csv
