#!/bin/bash
cat orders.csv | awk -F\; '
	NR==1{
		print $1";" $2";" $5";" $8
	}
	NR>1 && $5<"1995-03-15"{
		print $1";" $2";" $5";" $8
	}
' > tmporder.csv

cat lineitem.csv | awk -F\; '
	NR==1{
		print $1 ";revenue"
	}
	NR>1 && $5>"1995-03-15"{
		suma=($6*(1.0-$7));
		print $1 ";" suma
	}
' > tmpline.csv

join --header -t\; -1 1 -2 1 tmporder.csv  tmpline.csv > tmplo.csv

#header
head -1 tmplo.csv > tmp1.csv
sed -nr '1s/;.*//p' customer.csv | sort  > tmp2.csv

tail -n +2 tmplo.csv | sort -t\; -k2 >> tmp1.csv
sed -nr 's/^([^;]*);.*BUILDING;.*/\1/p' customer.csv >> tmp2.csv
join --header -t\; -1 2 -2 1 tmp1.csv  tmp2.csv > output.csv

rm tmpline.csv tmporder.csv tmplo.csv tmp1.csv tmp2.csv

# gruppieren und sortieren
cat output.csv | tr '.,' ',.' | datamash -H -t\; -g2,3,4 sum 5 -s
#| sort -t\; -k4 -r | sort -t\; -k2 | head -10
