#!/bin/bash
#oldIFS=$IFS
#IFS=,
#lookup
#i=1
#for e in head -n1; do
#  lookup[e]=i
#  $(($i+1))
#done
#IFS=\;
#cat $1 | tr '.,' ',;' |	sed '1s/$/;sumdiscp;sumcharge/'| awk -F\; '$11>"1996-03-13"&&NR>4
#			{print $0}' 
cat lineitem.csv | tr '.,' ',.' | awk -F\; '
	NR==1{
		print $0 ";sum_disc;sum_charge "
	}
	NR>1 && $11<="1998-9-2"{
		suma=($6*(1.0-$7));
		sumb=($6*(1.0-$7)*(1.0-$8));
		print $0 ";" suma ";" sumb
	}
' >tmp.csv
head -1 tmp.csv > tmp2.csv
tail -n+2 tmp.csv | sort -t\; -k9,10 >> tmp2.csv
cat tmp2.csv | datamash -t\; -H -g9,10 sum 5 sum 6 sum 17 sum 18 mean 5 mean 6 mean 7 count 1
