#!/bin/bash
## N >< S
head -1 supplier.csv | cut -d\; -f1,4 > tmp1.csv
tail -n+2 supplier.csv | cut -d\; -f1,4 | sort -t\; -k2 >> tmp1.csv
head -1 nation.csv | cut -d\; -f1 > tmp2.csv
tail -n+2 nation.csv | grep 'GERMANY' | cut -d\; -f1 >> tmp2.csv
join --header -t\; -1 2 -2 1 tmp1.csv tmp2.csv > tmpsn.csv

# PS ><  (partkey)
head -1 partsupp.csv | cut -d\; -f1,2,3,4 > tmp1.csv
tail -n+2 partsupp.csv | cut -d\; -f1,2,3,4 | sort -t\; -k2 >> tmp1.csv
head -1 tmpsn.csv | cut -d\; -f2 > tmp2.csv
tail -n+2 tmpsn.csv | cut -d\; -f2 | sort >> tmp2.csv
join --header -t\; -1 2 -2 1 tmp1.csv tmp2.csv > join.csv
sum=`awk -F\; '
	BEGIN{SUM=0}
	NR>1{SUM+=$3*$4}
	END{print SUM*0.0001}
' join.csv`
awk -F\; '
	NR==1{
		print $2";value"
	}
	NR>1 {
		mul=$3*$4
		print $2";"mul
	}
' join.csv | datamash -H -s -t\; -g1 sum 2 | awk -F\; "
	NR==1||\$2>$sum{
		print \$0
	}
"

rm tmp*.csv join.csv
