#!/bin/bash
# 2014-08-20
## R >< N >< S
# R >< N (regionkey)
cut nation.csv -d\| -f1-3 > tmp1.csv
cut nation.tbl -d\| -f1-3 | sort -t\| -k3,3 >> tmp1.csv
cut region.csv -d\| -f1 > tmp2.csv 
cat region.tbl | grep "EUROPE" | cut -d\| -f1 | sort >> tmp2.csv
join --header -t\| -1 3 -2 1 tmp1.csv tmp2.csv > tmprn.csv

# >< S (nationkey)
cut supplier.csv -d\| -f1-7 > tmp1.csv
cut supplier.tbl -d\| -f1-7 | sort -t\| -k4,4 >> tmp1.csv
head -1   tmprn.csv > tmp2.csv 
tail -n+2 tmprn.csv | sort -t\| -k2,2 >> tmp2.csv
join --header -t\| -1 4 -2 2 tmp1.csv tmp2.csv > tmprns.csv

# PS >< RNS (suppkey)
cut partsupp.csv -d\| -f1,2,4 > tmp1.csv
cut partsupp.tbl -d\| -f1,2,4 | sort -t\| -k2,2 >> tmp1.csv
head -1   tmprns.csv > tmp2.csv 
tail -n+2 tmprns.csv | sort -t\| -k2,2 >> tmp2.csv
join --header -t\| -1 2 -2 2 tmp1.csv tmp2.csv | tee join1.csv |\
# group by partkey: ps_supplycost = select min(ps_supplycost)
tr ',.' '.,' | datamash -H -s -t\| -g2 min 3 | tr ',.' '.,' > join2.csv

# P >< PRNS (partkey)
#part: restrictions: p_size = 15; residuals: p_type like %BRASS
cut part.csv -d\| -f1,2,3 > tmp1.csv
cat part.tbl | awk -F\| '
	$6==15 && $5~/.*BRASS/ {print $1,$2,$3}' OFS=\| |\
		 sort -t\| -k1,1 >> tmp1.csv
head -1   join2.csv > tmp2.csv 
tail -n+2 join2.csv | sort -t\| -k1,1 >> tmp2.csv
join --header -t\| -1 1 -2 1 tmp1.csv tmp2.csv > join3.csv

# >< PS (partkey)
cut partsupp.csv -d\| -f1,2,4 > tmp1.csv
cut partsupp.tbl -d\| -f1,2,4 | sort -t\| -k1,1 >> tmp1.csv
join --header -t\| -1 1 -2 1 tmp1.csv join3.csv | tee join4.csv |\
awk -F\| 'NR==1 || $3==$6 {print $0}' > join5.csv

# RNS >< P PS (suppkey)
head -1   tmprns.csv > tmp1.csv 
tail -n+2 tmprns.csv | sort -t\| -k2,2 >> tmp1.csv
head -1   join5.csv > tmp2.csv 
tail -n+2 join5.csv | sort -t\| -k2,2 >> tmp2.csv
join --header -t\| -1 2 -2 2 tmp1.csv tmp2.csv |\
awk -F\| '{print $6,$3,$9,$10,$12,$4,$5,$7}' OFS=\| > join6.csv

#s_acctbal,s_name,s_name,s_partkey,s_mfgr,s_address,s_phone,s_comment
head -1 join6.csv
tail -n+2 join6.csv | sort -t\| -k1,1 -nr

rm join{1,2,3,4,5,6}.csv tmp{1,2,rn,rns}.csv
