#!/bin/bash
## O >< C >< N1 >< R
# N1 >< R (regionkey)
head -1 region.csv | cut -d\; -f1 > tmpregion.csv
grep ';AMERICA;' region.csv | cut -d\; -f1 >> tmpregion.csv
head -1 nation.csv | cut -d\; -f1,3 > tmpnation.csv
tail -n+2 nation.csv | cut -d\; -f1,3 | sort -t\; -k2 >> tmpnation.csv
join --header -t\; -1 1 -2 2 tmpregion.csv tmpnation.csv > tmpnr.csv

# C >< (nationkey)
head -1 customer.csv | cut -d\; -f1,4 > tmp1.csv
tail -n+2 customer.csv | cut -d\; -f1,4 | sort -t\; -k2 >> tmp1.csv
head -1 tmpnr.csv > tmp2.csv
tail -n+2 tmpnr.csv | sort -t\; -k2 >> tmp2.csv
join --header -t\; -1 2 -2 2 tmp1.csv tmp2.csv > tmpocn1r.csv

# O >< (custkey)
cat orders.csv | awk -F\; '
	NR==1{
		print $1 ";" $2 ";year"
	}
	NR>1 && ( $5>="1995-01-01" && $5<="1996-12-31"){
		print $1 ";" $2 ";" substr($5,1,4)
	}
' > tmporder.csv
head -1 tmporder.csv  > tmp1.csv
tail -n+2 tmporder.csv  | sort -t\; -k2  >> tmp1.csv
head -1 tmpocn1r.csv > tmp2.csv
tail -n+2 tmpocn1r.csv | sort -t\; -k2 >> tmp2.csv
join --header -t\; -1 2 -2 2 tmp1.csv tmp2.csv > join1.csv

## P >< L >< S >< N2 (nationkey)
# S >< N2
head -1 supplier.csv | cut -d\; -f1,4 > tmp1.csv
tail -n+2 supplier.csv | cut -d\; -f1,4 | sort -t\; -k2 >> tmp1.csv
cut -d\; -f1,2  nation.csv |\
join --header -t\; -1 1 -2 2 - tmp1.csv > tmpsn.csv

# L >< P (partkey)
cat lineitem.csv | awk -F\; '
	NR==1{
		print $1 ";" $2 ";" $3 ";volume"
	}
	NR>1 && $11>="1995-01-01" && $11 <="1996-12-31"{
		suma=($6*(1.0-$7))
		print $1 ";" $3 ";" suma
	}
' > tmpline.csv
head -1 tmpline.csv > tmp1.csv
tail -n+2 tmpline.csv | sort -t\; -k2 >> tmp1.csv
head -1 part.csv | cut -d\; -f1 > tmp2.csv
tail -n+2 part.csv | grep 'ECONOMY'| cut -d\; -f1 >> tmp2.csv
join --header -t\; -1 2 -2 1 tmp1.csv tmp2.csv > join2.csv

# L >< O... (orderkey)
head -1 join2.csv > tmp1.csv
tail -n+2 join2.csv | sort -t\; -k2 >> tmp1.csv
head -1 join1.csv > tmp2.csv
tail -n+2 join1.csv | sort -t\; -k2 >> tmp2.csv
join --header -t\; -1 2 -2 2 tmp1.csv tmp2.csv > join3.csv

# L >< S (suppkey)
head -1 join3.csv > tmp1.csv
tail -n+2 join3.csv | sort -t\; -k3 >> tmp1.csv
head -1 tmpsn.csv > tmp2.csv
tail -n+2 tmpsn.csv | sort -t\; -k3 >> tmp2.csv
join --header -t\; -1 3 -2 3 tmp1.csv tmp2.csv > output.csv


cat output.csv | datamash -H -s -t\; -g6,10  sum 4 | awk  -F\; '
	NR==1{
		print $0 ";volume_g"
	}
	NR>1 && $2=='BRAZIL'{
		print $0 ";" $4
	}
	NR>1 && $2!='BRAZIL'{
		print $0 ";" 0
	}
' | datamash -H -s -t\; -g6 sum 3 sum 4 | awk  -F\; '
	NR==1{
		print $0
	}
	NR>1{
		print $0 ";" $2/$3
	}
'

rm tmp*.csv join1.csv join2.csv
