#!/bin/bash
# 2014-08-31
## N >< C >< O >< L
# O >< L (orderkey)
 #       o_orderkey = l_orderkey
  #$15      and l_shipmode in ('MAIL', 'SHIP')
   # $12<$13   and l_commitdate < l_receiptdate
    # $11<12    and l_shipdate < l_commitdate
     # $13  and l_receiptdate >= date '1994-01-01'
      # $13  and l_receiptdate < date '1995-01-01'
sort -t\| -k1,1 orders.tbl|\
cat orders.csv - | awk -F\| '
	NR==1{
		print $1 "|high_line_count|low_line_count"
	}
	NR>1{
		if ( $6=="1-URGENT"||$6=="2-HIGH" )
		  print $1 "|1|0"
		else
		  print $1 "|0|1"
	}
' > tmporder.csv

sort -t\| -k1,1 lineitem.tbl |\
cat lineitem.csv - | awk -F\| '
	NR==1{
		print $1 "|" $15
	}
	NR>1 && $13>="1994-01-01" && $13<"1995-01-01" && $12<$13 && $11<$12 && ($15=="MAIL" || $15=="SHIP"){
		print $1 "|" $15
	}
' > tmpline.csv

join --header -t\| -1 1 -2 1 tmporder.csv tmpline.csv > tmpjoin.csv
head -1 tmpjoin.csv > tmp1.csv
tail -n+2 tmpjoin.csv | sort -t\| -k4,4 | cat tmp1.csv - |\
#tr '.,' ',.' |\
datamash -H -s -t\| -g4 sum 2 sum 3
rm tmp*.csv
