#!/bin/bash
#2014-09-01
cat lineitem.* | awk -F\| '
	NR>1 && $11<="1998-9-2"{
		print $0 ($6*(1.0-$7)),($6*(1.0-$7)*(1.0+$8)),
	}
' > tmp.csv
head -1 tmp.csv > tmp1.csv
tail -n+2 tmp.csv | sort -t\| -k9,10 | cat tmp1.csv - |\
#tr '.,' ',.' |\
datamash -t\| -H -g9,10 sum 5 sum 6 sum 17 sum 18 mean 5 mean 6 mean 7 count 1
