#!/bin/bash
#2014-08-31
## N >< S >< L1 >< O |> L
cut -d\| -f1,2,4 supplier.csv > tmp1.csv
cut -d\| -f1,2,4 supplier.tbl | sort -t\| -k3,3 >> tmp1.csv
cut -d\| -f1 nation.csv > tmp2.csv
cat nation.tbl | grep "SAUDI" | cut -d\| -f1 >> tmp2.csv
join --header -t\| -1 3 -2 1 tmp1.csv tmp2.csv > tmpsn.csv

#l1.l_receiptdate > l1.l_commitdate
awk -F\| ' NR==1 || $13>$12 {print $1,$3} ' OFS=\| lineitem.* > tmpli.csv
head -1 tmpli.csv > tmp1.csv
tail -n+2 tmpli.csv | sort -t\| -k2,2 >> tmp1.csv
head -1 tmpsn.csv > tmp2.csv
tail -n+2 tmpsn.csv | sort -t\| -k2,2 >> tmp2.csv
join --header -t\| -1 2 -2 2 tmp1.csv tmp2.csv > join2.csv

#l1.l_receiptdate > l1.l_commitdate
head -1 orders.csv | cut -d\| -f1 > tmpA.csv
awk -F\| ' NR>=1 && $3=="F" {print $1} ' orders.tbl | sort >> tmpA.csv
head -1 join2.csv > tmpB.csv
tail -n+2 join2.csv | sort -t\| -k2,2 >> tmpB.csv
join --header -t\| -1 1 -2 2 tmpA.csv tmpB.csv > join3.csv

#l3.l_suppkey <> l1.l_suppkey
#awk -F\| 'NR==1 || $13>$12 {print $1,$3}' OFS=\| lineitem.csv > tmpli.csv
head -1 tmpli.csv > tmp2.csv
tail -n+2 tmpli.csv | sort -t\| -k1,1 >> tmp2.csv
join --header -t\| -1 1 -2 1 join3.csv tmp2.csv |\
 awk -F\| ' NR==1 || $2 != $5 {print $0} ' |\
join --header -t\| -1 1 -2 1 -v1 join3.csv - | cut -d\| -f1-4 > join4.csv

cut lineitem.tbl -d\| -f1-3 | sort -t\| -k1,1 | cut lineitem.csv - -d\| -f1,3 | datamash -H -t\| -g1 count 2 | awk -F\| '
	NR==1 || $2>1 {print $1} ' > tmp2.csv
join --header -t\| -1 1 -2 1 join4.csv tmp2.csv > join5.csv

head -1 join5.csv > tmp1.csv
tail -n+2 join5.csv | sort -t\| -k4,4 | cat tmp1.csv - |\
datamash -H -t\| -g4 count 1 > join6.csv

head -1 join6.csv
tail -n+2 join6.csv | sort -t\| -snr -k2,2 | head -99

rm tmp*.csv join*.csv
