#!/bin/bash
# 2014-08-31
#echo  'N >< S (nationkey)'
head -1 supplier.csv | cut -d\| -f1,4 > tmp2.csv
cat supplier.tbl | cut -d\| -f1,4 | sort -t\| -k2,2 >> tmp2.csv
cut -d\| -f1,2 nation.csv > tmp1.csv
cut -d\| -f1,2 nation.tbl | sort -t\| -k1,1 >> tmp1.csv
join --header -t\| -1 1 -2 2 tmp1.csv tmp2.csv > tmpsn.csv

#echo 'L >< P (partkey)'
head -1 lineitem.csv | cut -d\| -f1,2,3,5,6,7 > tmp1.csv
cat lineitem.tbl | cut -d\| -f1,2,3,5,6,7 | sort -t\| -k2,2 >> tmp1.csv
head -1 part.csv | cut -d\| -f1 > tmp2.csv
cat part.tbl | grep 'green'| cut -d\| -f1 | sort -t\| -k1,1 >> tmp2.csv
join --header -t\| -1 2 -2 1 tmp1.csv tmp2.csv > join1.csv

#echo 'join1 >< PS (partkey && suppkey)'
#_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount
sort -t\| -k1,1 partsupp.tbl | cut partsupp.csv - -d\| -f1,2,3,4 |\
join --header -t\| -1 1 -2 1 join1.csv - | awk -F\| '
	NR==1{
		print $2 "|" $3 "|amount"
	}
	NR>1 && $3==$7{
		sum=$5*(1.0-$6)-$9*$4
		print $2 "|" $3 "|" sum
	}
'> join2.csv

#echo 'join2 >< O (orderkey)'
head -1 join2.csv > tmp1.csv
tail -n+2 join2.csv | sort -t\| -k1,1 >> tmp1.csv
cut -d\| -f1,5 orders.csv > tmp2.csv
cut -d\| -f1,5 orders.tbl | sort -t\| -k1,1 >> tmp2.csv
join --header -t\| -1 1 -2 1 tmp1.csv tmp2.csv > join3.csv

#echo 'join3 >< SN (suppkey)'
head -1 join3.csv > tmp1.csv
tail -n+2 join3.csv | sort -t\| -k2,2 >> tmp1.csv
head -1 tmpsn.csv > tmp2.csv
tail -n+2 tmpsn.csv | sort -t\| -k3,3 >> tmp2.csv
join --header -t\| -1 2 -2 3 tmp1.csv tmp2.csv |\
 awk -F\| '
	NR==1{
		print $6 "|year|" $3
	}
	NR>1{
		print $6 "|" substr($4,1,4) "|"$3
	}
' > join4.csv

head -1 join4.csv > tmp1.csv
tail -n+2 join4.csv | sort -t\| -k1,2 | cat tmp1.csv - |\
#tr '.,' ',.'|\
datamash -H -t\| -g1,2 sum 3
#sort -t\| -k2,2 -r | sort -t\| -k1,1

rm tmp*.csv join1.csv join2.csv join3.csv join4.csv
