#!/bin/bash
cat professoren | cut -f1-3 - | grep sokrates | sort -k2
cut -f1-3 abcdef | grep soki > tmp1.csv
cat professoren | join -1 1 -2 2 erste - 
cut -f1-3 dererste | join -1 1 -2 2 derzweite - 
cat professoren | wc -l | juhu
mannoman | scho "wieder der Franz" mal zwei  
cat studenten | uniq

for i in a b c
do
	cat i
	emil und die Detektive
done
