#!/bin/bash
# 2014-08-26
mkfifo tmp1.csv tmp2.csv tmp.csv
## R >< N >< S
# R >< N (regionkey)
cat region.tbl | grep "EUROPE" | cut -d\| -f1 region.csv - |\
join --header -t\| -1 3 -2 1 <(
cut nation.csv -d\| -f1-3 > tmp.csv &
cut nation.tbl -d\| -f1-3 | sort -t\| -k3,3 | cat tmp.csv - 
) - > tmprn.csv

# >< S (nationkey)
head -1   tmprn.csv > tmp2.csv &
tail -n+2 tmprn.csv | sort -t\| -k2,2 | cat tmp2.csv - |\
join --header -t\| -1 4 -2 2 <(
cut supplier.tbl -d\| -f1-7 | sort -t\| -k4,4 | cut -d\| -f1-7 supplier.csv - 
) - > tmprns.csv

# PS >< RNS (suppkey)
head -1   tmprns.csv > tmp2.csv &
tail -n+2 tmprns.csv | sort -t\| -k2,2 | cat tmp2.csv - |\
join --header -t\| -1 2 -2 2 <(
cut partsupp.tbl -d\| -f1-4 | sort -t\| -k2,2 | cut -d\| -f1,2,4 partsupp.csv -
) - > join1.csv

# group by partkey (2): ps_supplycost = select min(ps_supplycost) (3)
head -1 join1.csv > tmp1.csv &
tail -n+2 join1.csv  | sort -t\| -k2,2 | cat tmp1.csv -  | awk -F\| '
	NR==1{print $2, "min("$3")"}
	NR==2{g2=$2; min=$3}
	NR>2{
		if( g2==$2 ){
			if(min>$3) 
				min=$3
		}else{
			print g2, min;
			g2=$2; min=$3;
		}
	}
	END{print $2,min}
' OFS=\| > join2.csv


# >< PS (partkey)
cut partsupp.csv -d\| -f1,2,4 > tmp1.csv &
cut partsupp.tbl -d\| -f1,2,4 | sort -t\| -k1,1 | cat tmp1.csv - |\
join --header -t\| -1 1 -2 1 - <(
head -1   join2.csv > tmp2.csv &
tail -n+2 join2.csv | sort -t\| -k1,1 | cat tmp2.csv - |\
join --header -t\| -1 1 -2 1 <(
cat part.tbl | awk -F\| '
	$6==15 && $5~/.*BRASS/ {print $1,$2,$3}' OFS=\| |\
	 sort -t\| -k1,1 | cut -d\| -f1,2,3 part.csv -
) -
) |\
awk -F\| 'NR==1 || $3==$6 {print $0}' > join5.csv 

# RNS >< P PS (suppkey)
head -1   join5.csv > tmp2.csv &
tail -n+2 join5.csv | sort -t\| -k2,2 | cat tmp2.csv - |\
join --header -t\| -1 2 -2 2 <(
head -1   tmprns.csv > tmp.csv &
tail -n+2 tmprns.csv | sort -t\| -k2,2 | cat tmp.csv -
) - |\
awk -F\| '{print $6,$3,$9,$10,$13,$4,$5,$7}' OFS=\| > join6.csv

#s_acctbal,s_name,s_name,s_partkey,s_mfgr,s_address,s_phone,s_comment
head -1 join6.csv
# sort s_acctbal desc,n_name,s_name,p_partkey
tail -n+2 join6.csv | sort -t\| -k1,1 -snr
rm join{1,2,3,5,6}.csv tmp{,1,2,rn,rns}.csv
