#!/bin/bash
#2014-08-27
cat lineitem.* | awk -F\| '
	NR==1{
		print "revenue"; sum=0;
	}
	NR>1 && $11>="1994-01-01" && $11<"1995-01-01" && $7>=0.05 && $7<=0.07 && $5<24{
		sum+=$6*$7;
	}
	END{print sum}
'
