#!/bin/bash
# 2014-08-20
# P >< PS (partkey)
cat partsupp.tbl | sort -t\| -k1,1 | cut -d\| -f1-5 partsupp.csv - > tmp1.csv
awk -F\| '$2~/^forest/{print $1}' part.tbl | sort -t\| -k1,1 | cut -d\| -f1 part.csv - |\
join --header -t\| -1 1 -2 1 tmp1.csv - > join1.csv

#l_shipdate >= date '1994-01-01' and l_shipdate < date '1995-01-01'
# and group by 
cat lineitem.tbl | sort -t\| -k2,3 | sort -t\| -k2,2 -s | cut -d\| -f2,3,5,11 lineitem.csv - | awk -F\| '
	NR==1{print $1,$2,"sum("$3")"}
	NR==2{g1=$1;g2=$2;sum=0}
	NR>2{
		if(g1!=$1 || g2!=$2){
			print g1,g2,sum;
			g1=$1; g2=$2; sum=0;
		}
	}
	NR>1 && $4>="1994-01-01" && $4<"1995-01-01"{
		sum+=$3;
	}
	END{print g1,g2,sum}
' OFS=\| |\
# L >< (l_partkey = ps_partkey)
join --header -t\| -1 1 -2 1 join1.csv - |\
# l_suppkey = ps_suppkey
awk -F\| 'NR==1 || ($2==$6 && $3>$7*0.5){print $2}' > join2.csv

#' S >< (suppkey in...)'
head -1 join2.csv > tmp2.csv
tail -n+2 join2.csv | sort - >> tmp2.csv
cat supplier.tbl | sort -t\| -k1,1 |\
cut -d\| -f1-7 supplier.csv -  |\
join --header -t\| -1 1 -2 1 - tmp2.csv > join3.csv

# S >< N (nationkey)
head -1 join3.csv > tmp1.csv
tail -n+2 join3.csv | sort -t\| -k4,4 >> tmp1.csv
awk -F\| 'NR==1 || $2=="CANADA"{print $1}' nation.* |\
join --header -t\| -1 4 -2 1 tmp1.csv - | cut -d\| -f3,4 > join4.csv

head -1 join4.csv
tail -n+2 join4.csv | sort -u

rm tmp*.csv join*.csv
