#!/bin/bash
#2014-08-20
cat lineitem.* | awk -F\| '
	NR==1{
		print $1 "|revenue"
	}
	NR>1 && $11>="1994-01-01" && $11<"1995-01-01" && $7>=0.05 && $7<=0.07 && $5<24{
		suma=$6*$7;
		print $1 "|" suma
	}
'| tr ',.' '.,' | datamash -H -t\| sum 2
