#!/bin/bash
# 2014-08-19
# PS >< P
#  $4  p_brand <> 'Brand#45'
#  $5      and p_type not like 'MEDIUM POLISHED%'
#  $6      and p_size in (49, 14, 23, 45, 19, 3, 36, 9)
sort -t\| -k1,1 part.tbl | cat part.csv - | awk -F\| '
	NR==1{
		print $1,$4,$5,$6
	}
	NR>1 && $4!="Brand#45" && $5!~/^MEDIUM POLISHED.*/ && ($6==49 || $6==14 || $6==23 || $6==45 || $6==19 || $6==3 || $6==36 || $6==9){
		print $1,$4,$5,$6
	}
' OFS=\| > tmppart.csv
sort -t\| -k1,1 partsupp.tbl | cut -d\| -f1-4 partsupp.csv - > tmpsupp.csv
join --header -t\| -1 1 -2 1 tmpsupp.csv tmppart.csv > join1.csv

# PS |> S (suppkey)
head -1 join1.csv | cut -d\| -f1,2,5,6,7,8 > tmp1.csv
tail -n+2 join1.csv |  cut -d\| -f1,2,5,6,7,8 | sort -t\| -k2,2 >> tmp1.csv
cut -d\| -f1 supplier.csv > tmp2.csv
sed -r '/Customer.*Complaints/ d' supplier.tbl | cut -d\| -f1 | sort >> tmp2.csv
join --header -t\| -1 2 -2 1 tmp1.csv tmp2.csv > join2.csv

#group by p_brand, p_type, p_size;  count(distinct ps_suppkey)
cat join2.csv | datamash -H -s -t\| -g3,4,5 countunique 1 > tmpout.csv

# supplier_cnt desc, p_brand, p_type, p_size
head -1 tmpout.csv; tail -n+2 tmpout.csv | sort | sort -t\| -nr -k4,4

rm tmp*.csv join1.csv join2.csv
