#!/bin/bash
# 2014-08-20
avg=`awk -F\| 'BEGIN{sum=0; cnt=0; print "avg"}
	NR>1 && $6>0 &&
	(substr($5,1,2)==13||substr($5,1,2)==31||
	substr($5,1,2)==23||substr($5,1,2)==29||
	substr($5,1,2)==30||substr($5,1,2)==18||
	substr($5,1,2)==17){
		sum+=$6; cnt+=1
	}
	END{print sum/cnt}
' customer.* | tail -1`

#c_acctbal > select avg(c_acctbal) from...
awk -F\| -v avg=$avg '
	NR==1{print $1,$6, "cntrycode"}
	NR>1 && $6>avg &&
	(substr($5,1,2)==13||substr($5,1,2)==31||
	substr($5,1,2)==23||substr($5,1,2)==29||
	substr($5,1,2)==30||substr($5,1,2)==18||
	substr($5,1,2)==17){
		print $1,$6,substr($5,1,2)
	}
' OFS=\| customer.* > tmpc.csv

# O |> C
head -1 tmpc.csv > tmp1.csv
tail -n+2 tmpc.csv | sort -t\| -k1,1 >> tmp1.csv
cut -d\| -f2 orders.csv > tmp2.csv
cut -d\| -f2 orders.tbl | sort >>tmp2.csv
join --header -t\| -v1 -o 0 1.2 1.3 tmp1.csv tmp2.csv |\
# group by
tr '.,' ',.' | datamash -t\| -s -H -g3 count 1 sum 2

rm tmp*.csv
