#!/bin/bash
sort -k1,1 -t\| orders.tbl | cat orders.csv - | awk -F\| '
	NR==1{
		print $1"|" $6
	}
	NR>1 && $5<"1993-10-01" && $5>="1993-07-01"{
		print $1"|" $6
	}
' > tmporder.csv

sort -k1,1 -t\| lineitem.tbl |cat lineitem.csv - | awk -F\| '
	NR==1 || $12<$13{
		print $1
	}
' | uniq  > tmpline.csv

join --header -t\| -1 1 -2 1 tmporder.csv tmpline.csv | tee tmp.csv |\

# count mittel uniq
cut -d\| -f2 | tail -n+2 | sort | uniq -c
rm tmpline.csv tmporder.csv
exit
# count mittels awk
head -1 tmp.csv > tmp1.csv
tail -n+2 tmp.csv  | sort -t\| -k2,2 | cat tmp1.csv - | awk -F\| '
	NR==1{print $2,"order_count"}
	NR==2{g2=$2; count=1}
	NR>2{
		if( g2==$2 ){
			count++
		}else{
			print g2, count;
			g2=$2;count=1;
		}
	}
	END{print g2,count}
' OFS=\|

rm tmp*.csv 
