#!/bin/bash
# 2014-08-28
# PS >< P
#  $4  p_brand <> 'Brand#45'
#  $5      and p_type not like 'MEDIUM POLISHED%'
#  $6      and p_size in (49, 14, 23, 45, 19, 3, 36, 9)
cat part.tbl | sort -t\| -k1,1 | cat part.csv - | awk -F\| '
	NR==1{
		print $1,$4,$5,$6
	}
	NR>1 && $4!="Brand#45" && $5!~/^MEDIUM POLISHED.*/ && ($6==49 || $6==14 || $6==23 || $6==45 || $6==19 || $6==3 || $6==36 || $6==9){
		print $1,$4,$5,$6
	}
' OFS=\| > tmppart.csv
cat partsupp.tbl | sort -t\| -k1,1 | cut -d\| -f1-4 partsupp.csv - |\
join --header -t\| -1 1 -2 1 - tmppart.csv > join1.csv

# PS |> S (suppkey)
head -1 join1.csv | cut -d\| -f1,2,5,6,7,8 > tmp1.csv
tail -n+2 join1.csv |  cut -d\| -f1,2,5,6,7,8 | sort -t\| -k2,2 >> tmp1.csv
sed -r '/Customer.*Complaints/ d' supplier.tbl | cut -d\| -f1 | sort | cut -d\| -f1 supplier.csv - |\
join --header -t\| -1 2 -2 1 tmp1.csv - > join2.csv

#group by p_brand, p_type, p_size;  count(distinct ps_suppkey)
head -1 join2.csv > tmp1.csv
tail -n+2 join2.csv  | sort | sort -s -t\| -k3,5 | cat tmp1.csv - | awk -F\| '
	NR==1{print $3,$4,$5, "uniqcount("$1")"}
	NR==2{g3=$3;g4=$4;g5=$5;c1=$1;count=1}
	NR>2{
		if(g3==$3 && g4==$4 && g5==$5){
			if(c1!=$1) count++;
			c1=$1;
		}else{
			print g3,g4,g5,count;
			g3=$3;g4=$4;g5=$5;c1=$1;count=1;
		}
	}
	END{print g3,g4,g5,count}
' OFS=\| >  tmpout.csv

# supplier_cnt desc, p_brand, p_type, p_size
head -1 tmpout.csv; tail -n+2 tmpout.csv | sort -s -t\| -nr -k4,4

rm tmp*.csv join1.csv join2.csv
