#!/bin/bash
# (N >< S) >< (P >< PS)
# >< L
# >< O

#echo  'N >< S (nationkey)'
cut -d\| -f1,2 nation.tbl | sort -t\| -k1,1 | cut -d\| -f1,2 nation.csv - > tmp1.csv
cut -d\| -f1-4 supplier.tbl | sort -t\| -k4,4 | cut -d\| -f1,4 supplier.csv - |\
join --header -t\| -1 1 -2 2 tmp1.csv - > tmpsn.csv

# P >< PS (partkey)
cat part.tbl | grep 'green'| cut -d\| -f1 | sort -t\| -k1,1 | cut -d\| -f1 part.csv - > tmp1.csv
cat partsupp.tbl | sort -t\| -k1,1 | cut -d\| -f1,2,4 partsupp.csv - |\
join --header -t\| -1 1 -2 1 tmp1.csv - > tmppps.csv

# SN >< PPS (suppkey)
head -1 tmppps.csv > tmp1.csv
tail -n+2 tmppps.csv | sort -t\| -k2,2 >> tmp1.csv
head -1 tmpsn.csv > tmp2.csv
tail -n+2 tmpsn.csv | sort -t\| -k3,3 | cat tmp2.csv - |\
join --header -t\| -1 2 -2 3 tmp1.csv - > join1.csv

# >< L (suppkey, dann partkey gleich?)
cut lineitem.tbl -d\| -f1-7 | sort -t\| -k3,3 | cut -d\| -f1,2,3,5,6,7 lineitem.csv - |\
join --header -t\| -1 3 -2 1 - join1.csv  | awk -F\| '
	NR==1 || $3==$7 {print $0}' > join2.csv

# >< O (orderkey)
head -1 join2.csv > tmp1.csv
tail -n+2 join2.csv | sort -t\| -k2,2 >> tmp1.csv
cat orders.tbl | sort -t\| -k1,1 | cut -d\| -f1,5 orders.csv - |\
join --header -t\| -1 2 -2 1 tmp1.csv - | tee join3.csv |\

#_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount
# extract year
awk -F\| '
	NR==1{
		print $10 "|year|amount"
	}
	NR>1{
		sum=$5*(1.0-$6)-$8*$4
		print $10 "|" substr($11,1,4) "|" sum
	}
'> join4.csv

# group by $6 (nation), year, sum_profit
head -1 join4.csv > tmp1.csv
tail -n+2 join4.csv  | sort -r -t\| -k2,2 | sort -t\| -s -k1,1 | cat tmp1.csv - | awk -F\| '
	NR==1{print $1, $2, "sum_profit"}
	NR==2{g1=$1; g2=$2; sum=$3}
	NR>2{
		if(g1==$1 && g2==$2){
			sum+=$3
		}else{
			print g1,g2,sum;
			g1=$1; g2=$2; sum=$3;
		}
	}
	END{print g1,g2,sum}
' OFS=\|

rm tmp*.csv join{1,2,3,4}.csv
