#!/bin/bash
# 2014-08-27
## R >< N >< C >< O >< L
# R >< N (regionkey)
cut nation.csv -d\| -f1-3 > tmp1.csv
cut nation.tbl -d\| -f1-3 | sort -t\| -k3,3 >> tmp1.csv
cat region.tbl | grep "ASIA" | cut -d\| -f1 | sort | cut -d\| -f1 region.csv - |\
join --header -t\| -1 3 -2 1 tmp1.csv - > tmprn.csv
# >< C (nationkey)
cut customer.csv -d\| -f1,4 > tmp1.csv
cut customer.tbl -d\| -f1,4 | sort -t\| -k2,2 >> tmp1.csv
head -1   tmprn.csv > tmp2.csv
tail -n+2 tmprn.csv | sort -t\| -k2,2 | cat tmp2.csv - |\
join --header -t\| -1 2 -2 2 tmp1.csv - > tmprnc.csv
# >< O (custkey)
cut orders.csv -d\| -f1,2,4 > tmp1.csv
cat orders.tbl | awk -F\| '$5>="1994-01-01" && $5<"1995-01-01"{print $0}'| cut -d\| -f1,2,4 | sort -t\| -k2,2 >> tmp1.csv
head -1   tmprnc.csv > tmp2.csv
tail -n+2 tmprnc.csv | sort -t\| -k2,2 | cat tmp2.csv - |\
join --header -t\| -1 2 -2 2 tmp1.csv - > join1.csv
# >< L (orderkey)
cut lineitem.csv -d\|  -f1,3,6,7 > tmp1.csv
cut lineitem.tbl -d\| -f1,3,6,7 | sort -t\| -k1,1 >> tmp1.csv
head -1   join1.csv > tmp2.csv 
tail -n+2 join1.csv | sort -t\| -k2,2 | cat tmp2.csv - |\
join --header -t\| -1 1 -2 2 tmp1.csv - > join2.csv
# >< S (suppkey) && c_nationkey==s_nationkey
cut supplier.csv -d\| -f1,4 > tmp1.csv
cut supplier.tbl -d\| -f1,4 | sort -t\| -k1,1 >> tmp1.csv
head -1   join2.csv > tmp2.csv
tail -n+2 join2.csv | sort -t\| -k2,2 | cat tmp2.csv - |\
join --header -t\| -1 1 -2 2 tmp1.csv - | awk -F\| '
NR==1 || $2==$8{print $0}
' > join3.csv
# group by n_name, sum revenue
head -1 join3.csv > tmp1.csv
tail -n+2 join3.csv  | sort -t\| -k10,10 | cat tmp1.csv - | awk -F\| '
	NR==1{print $10,"sum(revenue)"}
	NR==2{g10=$10; sum=$4*(1.0-$5)}
	NR>2{
		if( g10==$10 ){
			sum+=$4*(1.0-$5)
		}else{
			print g10, sum;
			g10=$10;sum=$4*(1.0-$5);
		}
	}
	END{print g10,sum}
' OFS=\| > join4.csv
head -1 join4.csv
tail -n+2 join4.csv | sort -t\| -k2,2 -r

rm join{1,2,3,4}.csv tmp{1,2,rn,rnc}.csv
