#!/bin/bash
# 2014-08-28
mkfifo tmp1.csv tmp2.csv join4.csv tmp.csv
## N >< S >< L1 >< O |> L
echo ' N >< S'
(cut -d\| -f1,2,4 supplier.csv > tmp.csv &
cut -d\| -f1,2,4 supplier.tbl | sort -t\| -k3,3 | cat tmp.csv - > tmp1.csv)&
cat nation.tbl | grep 'SAUDI ARABIA' | cut -d\| -f1 nation.csv - |\
join --header -t\| -1 3 -2 1 tmp1.csv - > tmpsn.csv

echo ' >< L1 (suppkey)'
#l1.l_receiptdate > l1.l_commitdate
(head -1 tmpsn.csv > tmp.csv &
tail -n+2 tmpsn.csv | sort -t\| -k2,2 | cat tmp.csv - > tmp2.csv)&
awk -F\| '$13>$12 {print $1,$2,$3}' OFS=\| lineitem.tbl |\
sort -t\| -k3,3 | cut -d\| -f1,3 lineitem.csv - | tee tmpli.csv |\
join --header -t\| -1 2 -2 2 - tmp2.csv > join2.csv

echo ' >< O (orderkey)'
#l1.l_receiptdate > l1.l_commitdate
(head -1 join2.csv > tmp.csv &
tail -n+2 join2.csv | sort -t\| -k2,2 | cat tmp.csv - > tmp2.csv)&
awk -F\| '$3=="F" {print $1}' orders.tbl | sort | cut -d\| -f1 orders.csv - |\
join --header -t\| -1 1 -2 2 - tmp2.csv > join3.csv

echo ' |> L3 (orderkey)'
#l3.l_suppkey <> l1.l_suppkey
#awk -F\| 'NR==1 || $13>$12 {print $1,$3}' OFS=\| lineitem.csv > tmpli.csv
(head -1 tmpli.csv > tmp2.csv &
tail -n+2 tmpli.csv | sort -t\| -k1,1 | cat tmp2.csv - |\
join --header -t\| -1 1 -2 1 join3.csv - |\
 awk -F\| 'NR==1 || $2!=$5 {print $0}' |\
join --header -t\| -1 1 -2 1 -v1 join3.csv - | cut -d\| -f1-4 > join4.csv)&

echo ' >< L2 ( l2.l_orderkey = l1.l_orderkey and l2.l_suppkey <> l1.l_suppkey)'
# gibt es vom jeweiligen l_orderkey mind. 2? group by, join
cut lineitem.tbl -d\| -f1,3 | sort -t\| -k1,1 | cut lineitem.csv - -d\| -f1,3 | awk -F\| '
	NR==1{print $1, "count(*)"}
	NR==2{g1=$1;count=1}
	NR>2{
		if(g1==$1){
			count++;
		}else {
			if(count>1)
				print g1,count;
			g1=$1;count=1;
		}
	}
	END{print g1,count}
' OFS=\| |\
join --header -t\| -1 1 -2 1 join4.csv - > join5.csv
# group by 4 count *
head -1 join5.csv > tmp1.csv &
tail -n+2 join5.csv  | sort -t\| -k3 | cat tmp1.csv - | awk -F\| '
	NR==1{print $4, "count(*)"}
	NR==2{g4=$4;count=1}
	NR>2{
		if(g4==$4){
			count++;
		}else{
			print g4,count;
			g4=$4;count=1;
		}
	}
	END{print g4,count}
' OFS=\| > join6.csv

head -1 join6.csv
tail -n+2 join6.csv | sort -t\| -snr -k2,2 | head -99

rm tmp*.csv join*.csv
